services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: db_test_admin
      POSTGRES_PASSWORD: OMPJ!i4Bjr2btCrwKz2_TdjruUAqah
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U db_test_admin -d db_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: docker.io/taapi/taapi-bdd:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:9000"
